version: '3'

services:
  jackett:
    image: linuxserver/jackett:latest
    volumes:
      - ./jackett:/config
    ports:
      - '9117:9117'
      - '9118:9118'
  sonarr:
    image: linuxserver/sonarr:latest
    volumes:
      - ./sonarr:/config
      - ${DOWNLOADS_FOLDER}:/downloads/complete
      - ${SERIES_FOLDER}:/tv
    ports:
      - '8989:8989'
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
  radarr:
    image: linuxserver/radarr:latest
    volumes:
      - ./radarr:/config
      - ${DOWNLOADS_FOLDER}:/downloads/complete
      - ${MOVIES_FOLDER}:/movies
    ports:
      - '7878:7878'
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
  transmission:
    image: linuxserver/transmission:latest
    volumes:
      - ./transmission:/config
      - ${DOWNLOADS_FOLDER}:/downloads/complete
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ='Europe/Madrid'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'