version: '3.7'

services:
  jackett:
    image: linuxserver/jackett:latest
    volumes:
      - ./jackett:/config
    ports:
      - '9117:9117'
      - '9118:9118'
  sonarr:
    image: linuxserver/sonarr:latest
    volumes:
      - ./sonarr:/config
      - ./downloads:/downloads/complete
      - ./series:/tv
    ports:
      - '8989:8989'
    environment:
      - PGID=20
      - PUID=501
  transmission:
    image: linuxserver/transmission:latest
    volumes:
      - ./transmission:/config
      - ./downloads:/downloads/complete
      - ./watch:/watch
    ports:
      - '9091:9091'
      - '51413:51413'
      - '51413:51413/udp'
    environment:
      - PGID=20
      - PUID=501
      - TZ='Europe/Madrid'